api_id: 25209488
api_hash: e7dbae9e7b73a0113732d6fb04cabc25
bot_token: 6372570235:AAG-M07aJQblGQMYlE873-uy493XZqzqzCw
database_url: postgresql://postgres.kbgeqqezvwoqafbkjkdc:Hasan@#4455@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
owner_id: 5556908572
message_dump: -1001786848035
telethon_client: BQFaHUYAOhy1p2TcWlBmOJe4iWtdqGiG48rJ1EnPSa1HcmWImyrvr8NJkBvnVq59QVaxmX4wOsq7RWd2g6Rw8jn9NE1rasXJiK3tu8xDpGbABkesXbVdKcCzgAwonTDnARX6w33tz7MBdB7tSwmxFXSDvQRIqCY12tcV5xmcmJ_HPcYv_665aKYY2Zq8_7ODUCzYei7L1Y21mLV7Pm1Y7LHLNjgFuXnQZta69xygYC1pakBcDi9U7zrWTT4oN0VRunpyoPeXoCoxc5cafgUnKoAarQEQKmXplJPfNrmDSgnAczor2-c4EpqQxUXAHGdM3EpG7qW-A4UFz5Hf2CQfvXhMLI4G1gAAAAGZIN71AA
spamwatch_api: bBfQ_4C99ryQNJkf~y69s_TlmFK8mTtc~UWCHPoWmjj66gZgOq_T5WJlB2qURdtE
whitelist_users: 5556908572
